name: GemsEconomy
main: me.xanium.gemseconomy.GemsEconomy
version: 4.9.2
author: Xanium
description: A multi-currency economy plugin for spigot servers!
website: https://www.spigotmc.org/resources/gemseconomy.19655/
load: STARTUP
api-version: 1.16
loadbefore:
  - ItemFrameShops
softdepend: [Vault]
commands:
  gbalance:
    description: Shows your balances
    usage: /balance (account)
    aliases: [gbal, gmoney]
  gbaltop:
    description: Shows the top balances of the server
    usage: /baltop (currency) (page)
    aliases: [gmoneytop, gecotop, gtop, gbaltop]
  gcurrency:
    description: Manage the currencies.
    usage: /currency
    aliases: [gcurr, gemscurrencies, currencies]
  gemserconomy:
    description: Give, set or take currency.
    usage: /eco <set|take|give> <account> <amount> (currency)
    aliases: [geconomy, geco]
  gpay:
    description: Pays another account
    usage: /pay <account> <amount> (currency)
    aliases: [gemspay]
  cheque:
    usage: /cheque
    description: Write or Redeem a cheque.
    aliases: [note, banknote]
  exchange:
    usage: /exchange
    description: Exchange currencies.
    aliases: [gex, gemsexchange, gexchange]